"""add brand profiles and creative generation tables

Revision ID: 59f59a291c8a
Revises: af3c705f0308
Create Date: 2026-08-21 15:38:24.094432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59f59a291c8a'
down_revision: Union[str, Sequence[str], None] = 'af3c705f0308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_profiles',
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=255), nullable=False),
    sa.Column('audience_primary', sa.Text(), nullable=False),
    sa.Column('audience_secondary', sa.Text(), nullable=False),
    sa.Column('tone', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('visual_identity', sa.JSON(), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('compliance_mandatory_disclaimer', sa.Text(), nullable=False),
    sa.Column('compliance_secondary_disclaimers', sa.JSON(), nullable=False),
    sa.Column('compliance_banned_claims', sa.JSON(), nullable=False),
    sa.Column('compliance_rules', sa.JSON(), nullable=False),
    sa.Column('cta_bank', sa.JSON(), nullable=False),
    sa.Column('hashtag_bank', sa.JSON(), nullable=False),
    sa.Column('product_lines', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_brand_profiles_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_brand_profiles_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_profiles')),
    sa.UniqueConstraint('project_id', name='uq_brand_profiles_project_id')
    )
    op.create_index(op.f('ix_brand_profiles_project_id'), 'brand_profiles', ['project_id'], unique=False)
    op.create_table('creative_briefs',
    sa.Column('campaign_id', sa.CHAR(length=36), nullable=False),
    sa.Column('product_line', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('format', sa.Enum('post', 'carousel', 'reel', name='creativeformat', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('carousel_slides', sa.Integer(), nullable=True),
    sa.Column('reel_duration_s', sa.Integer(), nullable=True),
    sa.Column('language', sa.Enum('en', 'hi', 'hinglish', name='creativelanguage', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('concept_count', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Enum('draft', 'standard', 'hero', name='creativequality', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('extra_notes', sa.Text(), nullable=False),
    sa.Column('voiceover', sa.Enum('native_audio', 'silent_text', name='voiceovermode', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('job_key', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_creative_briefs_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_creative_briefs_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creative_briefs'))
    )
    op.create_index(op.f('ix_creative_briefs_campaign_id'), 'creative_briefs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_creative_briefs_job_key'), 'creative_briefs', ['job_key'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('brief_id', sa.CHAR(length=36), nullable=False),
    sa.Column('campaign_id', sa.CHAR(length=36), nullable=False),
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('company_id', sa.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'partially_failed', name='generationjobstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('estimated_cost_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_cost_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.CHAR(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('finished_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('arq_job_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['creative_briefs.id'], name=op.f('fk_generation_jobs_brief_id_creative_briefs')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_generation_jobs_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_generation_jobs_company_id_companies')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_generation_jobs_project_id_projects')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_generation_jobs_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_jobs'))
    )
    op.create_index(op.f('ix_generation_jobs_brief_id'), 'generation_jobs', ['brief_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_campaign_id'), 'generation_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_company_id'), 'generation_jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_project_id'), 'generation_jobs', ['project_id'], unique=False)
    op.create_table('creative_concepts',
    sa.Column('job_id', sa.CHAR(length=36), nullable=False),
    sa.Column('concept_index', sa.Integer(), nullable=False),
    sa.Column('angle', sa.String(length=64), nullable=False),
    sa.Column('hook', sa.String(length=120), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('cta', sa.String(length=255), nullable=False),
    sa.Column('on_image_headline', sa.String(length=60), nullable=False),
    sa.Column('on_image_subhead', sa.String(length=90), nullable=False),
    sa.Column('on_image_kicker', sa.String(length=30), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('reel_script', sa.JSON(), nullable=True),
    sa.Column('carousel_slides', sa.JSON(), nullable=True),
    sa.Column('disclaimer_line', sa.Text(), nullable=False),
    sa.Column('compliance_notes', sa.JSON(), nullable=False),
    sa.Column('compliance_rejected', sa.Boolean(), nullable=False),
    sa.Column('compliance_rejection_reason', sa.Text(), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'rejected', name='conceptreviewstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reviewed_by', sa.CHAR(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], name=op.f('fk_creative_concepts_job_id_generation_jobs')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_creative_concepts_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creative_concepts'))
    )
    op.create_index(op.f('ix_creative_concepts_job_id'), 'creative_concepts', ['job_id'], unique=False)
    op.create_table('creative_assets',
    sa.Column('concept_id', sa.CHAR(length=36), nullable=False),
    sa.Column('kind', sa.Enum('image', 'video', 'raw_clip', name='creativeassetkind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('estimated_cost_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_cost_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('generated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['creative_concepts.id'], name=op.f('fk_creative_assets_concept_id_creative_concepts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creative_assets'))
    )
    op.create_index(op.f('ix_creative_assets_concept_id'), 'creative_assets', ['concept_id'], unique=False)
    # ### end Alembic commands ###

    # Autogenerate also flagged every other enum-backed CHECK constraint in
    # the schema as "removed" here - a MariaDB CHECK-constraint reflection
    # quirk (see the prior migrations), not a real diff. None of those enums
    # changed in this revision, so left untouched.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creative_assets_concept_id'), table_name='creative_assets')
    op.drop_table('creative_assets')
    op.drop_index(op.f('ix_creative_concepts_job_id'), table_name='creative_concepts')
    op.drop_table('creative_concepts')
    op.drop_index(op.f('ix_generation_jobs_project_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_company_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_campaign_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_brief_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_creative_briefs_job_key'), table_name='creative_briefs')
    op.drop_index(op.f('ix_creative_briefs_campaign_id'), table_name='creative_briefs')
    op.drop_table('creative_briefs')
    op.drop_index(op.f('ix_brand_profiles_project_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    # ### end Alembic commands ###
