"""add reel style and brand avatar columns

Revision ID: 7473bcd6200e
Revises: eb6e9ddc1bda
Create Date: 2026-08-21 17:37:59.227217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7473bcd6200e'
down_revision: Union[str, Sequence[str], None] = 'eb6e9ddc1bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_profiles', sa.Column('avatar_storage_key', sa.String(length=500), nullable=True))
    op.add_column('brand_profiles', sa.Column('avatar_mime_type', sa.String(length=128), nullable=True))
    op.add_column('creative_briefs', sa.Column('reel_style', sa.Enum('story', 'avatar', name='reelstyle', native_enum=False, create_constraint=True, length=32), nullable=True))
    # ### end Alembic commands ###

    # Autogenerate also flagged every other enum-backed CHECK constraint in
    # the schema as "removed" here - a MariaDB CHECK-constraint reflection
    # quirk (see the prior migrations), not a real diff. None of those enums
    # changed in this revision, so left untouched.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creative_briefs', 'reel_style')
    op.drop_column('brand_profiles', 'avatar_mime_type')
    op.drop_column('brand_profiles', 'avatar_storage_key')
    # ### end Alembic commands ###
