"""otp based email verification

Revision ID: 93f679352044
Revises: 307528e2fbc4
Create Date: 2026-08-28 22:24:43.747585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93f679352044'
down_revision: Union[str, Sequence[str], None] = '307528e2fbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_otps',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('used_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_otps_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_otps'))
    )
    op.create_index(op.f('ix_email_verification_otps_user_id'), 'email_verification_otps', ['user_id'], unique=False)
    # DROP TABLE removes its indexes/FKs implicitly in MySQL -- dropping the
    # index first fails (1553: needed in a foreign key constraint).
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###

    # Autogenerate also flagged every enum-backed CHECK constraint in the
    # schema as "removed" here -- the same MariaDB CHECK-constraint
    # reflection quirk noted in prior migrations, not a real diff. None of
    # those enums changed in this revision, so left untouched.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('token_hash', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('used_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.drop_table('email_verification_otps')
    # ### end Alembic commands ###
