"""product invitations and social account scope

Revision ID: ab84dbaa5c86
Revises: a15657c53873
Create Date: 2026-08-28 23:11:58.375175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab84dbaa5c86'
down_revision: Union[str, Sequence[str], None] = 'a15657c53873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('scope', sa.Enum('product', 'sub_products', 'company', name='socialaccountscope', native_enum=False, create_constraint=True, length=32), nullable=False))
    op.add_column('social_accounts', sa.Column('sub_product_ids', sa.JSON(), nullable=False))
    op.add_column('social_accounts', sa.Column('connection_method', sa.Enum('oauth', 'manual', name='socialconnectionmethod', native_enum=False, create_constraint=True, length=32), nullable=False))
    # ### end Alembic commands ###

    # Autogenerate also flagged every enum-backed CHECK constraint in the
    # schema as "removed" here -- the same MariaDB CHECK-constraint
    # reflection quirk noted in prior migrations, not a real diff. No
    # existing rows in social_accounts (verified against the dev DB), so
    # the new NOT NULL columns need no backfill/server_default.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('social_accounts', 'connection_method')
    op.drop_column('social_accounts', 'sub_product_ids')
    op.drop_column('social_accounts', 'scope')
