"""company approval, social accounts, drop invitations

Revision ID: c1222c983e76
Revises: 319f1a029b00
Create Date: 2026-08-18 12:40:43.753532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c1222c983e76'
down_revision: Union[str, Sequence[str], None] = '319f1a029b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'facebook', 'youtube', 'google', 'twitter', 'linkedin', name='socialplatform', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', name='socialaccountstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('added_by', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_social_accounts_added_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_social_accounts_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_accounts')),
    sa.UniqueConstraint('project_id', 'platform', 'handle', name='uq_social_accounts_project_platform_handle')
    )
    op.create_index(op.f('ix_social_accounts_project_id'), 'social_accounts', ['project_id'], unique=False)
    op.add_column('companies', sa.Column('approved_by', sa.CHAR(length=36), nullable=True))
    op.add_column('companies', sa.Column('approved_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True))
    op.add_column('companies', sa.Column('rejected_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True))
    op.add_column('companies', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_companies_approved_by_users'), 'companies', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###

    # The two enums that actually gained/lost values — their CHECK
    # constraints need to match the new allowed set. (Autogenerate also
    # flagged company_role/project_role/project_status/refresh_token_
    # revoked_reason/user_status as "removed" here, which is a MariaDB
    # CHECK-constraint reflection quirk, not a real diff — left untouched.)
    op.drop_constraint(op.f('ck_companies_companystatus'), 'companies', type_='check')
    op.create_check_constraint(
        op.f('ck_companies_companystatus'),
        'companies',
        "`status` in ('pending_approval','active','rejected','suspended')",
    )
    op.drop_constraint(op.f('ck_company_members_companymemberstatus'), 'company_members', type_='check')
    op.create_check_constraint(
        op.f('ck_company_members_companymemberstatus'),
        'company_members',
        "`status` in ('active','suspended')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_company_members_companymemberstatus'), 'company_members', type_='check')
    op.create_check_constraint(
        op.f('ck_company_members_companymemberstatus'),
        'company_members',
        "`status` in ('invited','active','suspended')",
    )
    op.drop_constraint(op.f('ck_companies_companystatus'), 'companies', type_='check')
    op.create_check_constraint(
        op.f('ck_companies_companystatus'), 'companies', "`status` in ('active','suspended')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_companies_approved_by_users'), 'companies', type_='foreignkey')
    op.drop_column('companies', 'rejection_reason')
    op.drop_column('companies', 'rejected_at')
    op.drop_column('companies', 'approved_at')
    op.drop_column('companies', 'approved_by')
    op.drop_index(op.f('ix_social_accounts_project_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
