"""add dry_run to generation_jobs

Revision ID: eb6e9ddc1bda
Revises: 59f59a291c8a
Create Date: 2026-08-21 16:01:38.492504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6e9ddc1bda'
down_revision: Union[str, Sequence[str], None] = '59f59a291c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('dry_run', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

    # Autogenerate also flagged every other enum-backed CHECK constraint in
    # the schema as "removed" here - a MariaDB CHECK-constraint reflection
    # quirk (see the prior migrations), not a real diff. None of those enums
    # changed in this revision, so left untouched.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_jobs', 'dry_run')
    # ### end Alembic commands ###
